-- Find the total customers by countries
select
country,
COUNT(customer_key) AS total_customer
from dbo.dim_customers
GROUP BY country
ORDER BY total_customer DESC


-- Find the total customers by gender
select
gender,
COUNT(customer_key) AS total_customer
from dbo.dim_customers
GROUP BY gender
ORDER BY total_customer DESC


-- Find the total products by category
select
category,
COUNT(product_key) AS total_product
from dbo.dim_products
GROUP BY category
ORDER BY total_product DESC


-- What is the average cost in each category?
select
category,
AVG(cost) AS avg_cost
from dbo.dim_products
GROUP BY category
ORDER BY avg_cost DESC


-- What is the total revenue generated by each category?
SELECT
p.category,
sum(f.sales_amount) total_revenue
from dbo.fact_sales f
LEFT JOIN dbo.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC


-- Find the total revenue is generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) AS total_revenue
from dbo.fact_sales s
LEFT JOIN dbo.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- What the distribution of sold items across countries?
SELECT 
c.country,
sum(s.quantity) AS total_sold_item
from dbo.fact_sales s
LEFT JOIN dbo.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY
c.country
ORDER BY total_sold_item DESC
